"""Generate executable Python step plans for Celatlas workflows.

The Python engine uses these plans for dry runs, preflight checks, resume
decisions, and real step execution.
"""

from __future__ import annotations

import os
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .config import get_config_value
from .fastq import FastqInputs, detect_job_fastqs
from .methods import get_method_module
from .paths import RuntimePaths, find_he_image, resolve_runtime_paths
from .planner import PlanError, build_effective_config, normalize_job_row, normalize_pipeline, normalize_workflow


ENHANCE_PARAMS = '{"p_low":5, "p_high":95, "suppress_noise":true, "noise_threshold":"auto"}'


@dataclass(frozen=True)
class StepPlan:
    name: str
    command: list[str]
    outputs: tuple[Path, ...] = ()

    def command_text(self) -> str:
        return shlex.join(self.command)


def build_step_plans(
    row: dict[str, str],
    config: dict[str, Any] | None = None,
    *,
    include_downstream: bool = True,
    validate_fastq: bool = False,
    allow_missing_fastq: bool = True,
) -> list[StepPlan]:
    row = normalize_job_row(row)
    config = build_effective_config(row, config or {})
    workflow = normalize_workflow(row.get("workflow", ""))
    pipeline = normalize_pipeline(row.get("pipeline"))
    paths = resolve_runtime_paths(row, config)
    values = _values(row, config, workflow, paths)

    if pipeline == "report":
        return _report_steps(paths, values)
    if pipeline == "reanalysis":
        return _build_reanalysis_steps(paths, values, include_downstream=include_downstream)
    return _build_upstream_steps(row, config, paths, values, include_downstream, validate_fastq, allow_missing_fastq)


def filter_step_plans(
    plans: list[StepPlan],
    *,
    from_step: str | None = None,
    to_step: str | None = None,
    only_steps: str | list[str] | tuple[str, ...] | None = None,
) -> list[StepPlan]:
    """Filter generated step plans by stable step name selectors."""

    if only_steps:
        selectors = _normalize_step_selectors(only_steps)
        missing = [selector for selector in selectors if not any(_step_matches(plan.name, selector) for plan in plans)]
        if missing:
            raise ValueError(f"Step selector not found: {', '.join(missing)}")
        return [plan for plan in plans if any(_step_matches(plan.name, selector) for selector in selectors)]

    start_index = _selector_index(plans, from_step, default=0)
    end_index = _selector_index(plans, to_step, default=len(plans) - 1)
    if start_index > end_index:
        return []
    return plans[start_index : end_index + 1]


def _build_upstream_steps(
    row: dict[str, str],
    config: dict[str, Any],
    paths: RuntimePaths,
    values: dict[str, Any],
    include_downstream: bool,
    validate_fastq: bool,
    allow_missing_fastq: bool,
) -> list[StepPlan]:
    try:
        fastqs = detect_job_fastqs(row, config, validate_files=validate_fastq)
    except FileNotFoundError:
        if not allow_missing_fastq:
            raise
        fastqs = _planned_fastqs(paths)
    assert fastqs is not None

    sample = paths.sample
    sampledir = paths.sampledir
    genome = str(paths.genome_dir)
    thread = str(values["thread"])
    barcode_r2 = sampledir / "01.barcode" / f"{sample}_2.fq.gz"
    cutadapt_r2 = sampledir / "02.cutadapt" / f"{sample}_clean_2.fq.gz"
    star_bam = sampledir / "03.star" / f"{sample}_Aligned.sortedByCoord.out.bam"
    featurecounts_bam = sampledir / "04.featureCounts" / f"{sample}_nameSorted.bam"
    count_detail = sampledir / "05.count" / f"{sample}_count_detail.txt"

    count_outputs: tuple[Path, ...] = (count_detail,)
    if paths.mode == "scrna":
        # The scRNA analysis step consumes the filtered matrix generated by
        # count. Declare it as a planned output so execution preflight knows
        # it will exist after 05.count instead of requiring it beforehand.
        count_outputs += (
            sampledir / "05.count" / f"{sample}_filtered_feature_bc_matrix",
        )

    steps = [
        StepPlan(
            "00.sample",
            [
                "celatlas_spatial",
                "rna",
                "sample",
                "--outdir",
                str(sampledir / "00.sample"),
                "--sample",
                sample,
                "--thread",
                thread,
                "--chemistry",
                paths.chemistry,
                "--fq1",
                str(fastqs.sample_fq1),
            ],
            outputs=(sampledir / "00.sample" / "step.log",),
        ),
        StepPlan(
            "01.barcode",
            _barcode_command(paths, values, fastqs.fq1_csv, fastqs.fq2_csv),
            outputs=(
                sampledir / "01.barcode" / f"{sample}_1.fq.gz",
                sampledir / "01.barcode" / f"{sample}_2.fq.gz",
            ),
        ),
        StepPlan(
            "02.cutadapt",
            _cutadapt_command(paths, values, str(barcode_r2)),
            outputs=(cutadapt_r2,),
        ),
        StepPlan(
            "03.star",
            _star_command(paths, values, str(cutadapt_r2)),
            outputs=(star_bam,),
        ),
        StepPlan(
            "04.featureCounts",
            [
                "celatlas_spatial",
                "rna",
                "featureCounts",
                "--outdir",
                str(sampledir / "04.featureCounts"),
                "--sample",
                sample,
                "--thread",
                str(values["featurecounts_thread"]),
                "--gtf_type",
                str(values["feature_type"]),
                "--genomeDir",
                genome,
                "--featureCounts_param",
                str(values["featurecounts_param"]),
                "--input",
                str(star_bam),
            ],
            outputs=(featurecounts_bam,),
        ),
        StepPlan(
            "05.count",
            _count_command(paths, values, str(featurecounts_bam)),
            outputs=count_outputs,
        ),
    ]

    if include_downstream:
        steps.extend(_downstream_steps(paths, values, str(count_detail)))
    return steps


def _build_reanalysis_steps(
    paths: RuntimePaths,
    values: dict[str, Any],
    *,
    include_downstream: bool,
) -> list[StepPlan]:
    if not include_downstream:
        return []
    if values["skip_binsegment"]:
        steps: list[StepPlan] = []
    else:
        steps = [_binsegment_step(paths, values, str(paths.sampledir / "05.count" / f"{paths.sample}_count_detail.txt"))]
    steps.extend(_post_binsegment_steps(paths, values))
    if not values["skip_analysis"]:
        steps.extend(_analysis_steps(paths, values))
    if not values["skip_report"]:
        steps.extend(_report_steps(paths, values))
    return steps


def _downstream_steps(paths: RuntimePaths, values: dict[str, Any], count_detail: str) -> list[StepPlan]:
    if paths.mode == "scrna":
        matrix_dir = paths.sampledir / "05.count" / f"{paths.sample}_filtered_feature_bc_matrix"
        steps = [
            StepPlan(
                "06.analysis_wrapper",
                [
                    "celatlas_spatial",
                    "rna",
                    "analysis",
                    "--outdir",
                    str(paths.sampledir / "06_analysis_wrapper"),
                    "--sample",
                    paths.sample,
                    "--thread",
                    str(values["thread"]),
                    "--genomeDir",
                    str(paths.genome_dir),
                    "--matrix_file",
                    str(matrix_dir),
                    "--assay",
                    "scrna",
                ],
                outputs=(paths.sampledir / "06_analysis_wrapper",),
            )
        ]
        steps.extend(_report_steps(paths, values))
        return steps
    steps = [_binsegment_step(paths, values, count_detail)]
    steps.extend(_post_binsegment_steps(paths, values))
    steps.extend(_analysis_steps(paths, values))
    if not values["skip_report"]:
        steps.extend(_report_steps(paths, values))
    return steps


def _barcode_command(paths: RuntimePaths, values: dict[str, Any], fq1_csv: str, fq2_csv: str) -> list[str]:
    barcode_mode = "scrna" if paths.mode == "scrna" else "strna"
    command = [
        "celatlas_spatial",
        "rna",
        "barcode",
        "--outdir",
        str(paths.sampledir / "01.barcode"),
        "--sample",
        paths.sample,
        "--thread",
        str(values["thread"]),
        "--chemistry",
        paths.chemistry,
        "--pattern",
        str(values["chemistry_pattern"]),
    ]
    if barcode_mode == "strna":
        input_dir = values["spatial_input_dir"]
        h5 = input_dir / f"{paths.sample}.barcodeToPos.h5"
        csv_path = input_dir / f"{paths.sample}_FilterBarcodes.csv"
        command.extend(["--whitelist", str(h5 if h5.exists() else csv_path)])
        bbox = input_dir / f"{paths.sample}_tissue_bbox.csv"
        if bbox.exists():
            command.extend(["--tissue-bbox", str(bbox)])
    command.extend(
        [
            "--mode",
            barcode_mode,
            "--lowNum",
            str(values["barcode_lownum"]),
            "--gzip",
            "--output_R1",
            "--resume",
        ]
    )
    if values["bbv4_strna_barcode_mismatch"] is not None:
        command.extend(["--bbv4-strna-barcode-mismatch", str(values["bbv4_strna_barcode_mismatch"])])
    if "," in fq1_csv:
        command.extend(["--max_parallel_files", str(values["max_parallel_files"])])
    command.extend(["--fq1", fq1_csv, "--fq2", fq2_csv])
    return command


def _cutadapt_command(paths: RuntimePaths, values: dict[str, Any], barcode_r2: str) -> list[str]:
    command = [
        "celatlas_spatial",
        "rna",
        "cutadapt",
        "--outdir",
        str(paths.sampledir / "02.cutadapt"),
        "--sample",
        paths.sample,
        "--thread",
        str(values["thread"]),
        "--minimum_length",
        str(values["cutadapt_min_length"]),
        "--nextseq_trim",
        str(values["cutadapt_nextseq_trim"]),
        "--gzip",
        "--overlap",
        str(values["cutadapt_overlap"]),
        "--insert",
        str(values["insert_r2"]),
    ]
    if values["cutadapt_param"]:
        command.extend(["--cutadapt_param", str(values["cutadapt_param"])])
    command.extend(["--fq", barcode_r2])
    return command


def _star_command(paths: RuntimePaths, values: dict[str, Any], cutadapt_r2: str) -> list[str]:
    return [
        "celatlas_spatial",
        "rna",
        "star",
        "--outdir",
        str(paths.sampledir / "03.star"),
        "--sample",
        paths.sample,
        "--thread",
        str(values["star_thread"]),
        "--genomeDir",
        str(paths.genome_dir),
        "--outFilterMatchNmin",
        str(values["star_match_min"]),
        "--outFilterMultimapNmax",
        str(values["star_multimap"]),
        "--STAR_param",
        f"--outFilterMatchNminOverLread {values['star_match_ratio']} --outFilterScoreMinOverLread {values['star_score_ratio']}",
        "--starMem",
        "30",
        "--fq",
        cutadapt_r2,
    ]


def _count_command(paths: RuntimePaths, values: dict[str, Any], featurecounts_bam: str) -> list[str]:
    command = [
        "celatlas_spatial",
        "rna",
        "count",
        "--outdir",
        str(paths.sampledir / "05.count"),
        "--sample",
        paths.sample,
        "--thread",
        str(values["thread"]),
        "--genomeDir",
        str(paths.genome_dir),
        "--expected_cell_num",
        str(values["cell_num"]),
        "--cell_calling_method",
        "auto",
        "--bam",
        featurecounts_bam,
        "--force_cell_num",
        "None",
    ]
    if values["resolve_multigene_umi"]:
        command.append("--resolve-multigene-umi")
    return command


def _binsegment_step(paths: RuntimePaths, values: dict[str, Any], count_detail: str) -> StepPlan:
    input_dir = values["spatial_input_dir"]
    outdir = paths.sampledir / "06.segment/01.binsegment"
    command = [
        "celatlas_spatial",
        "rna",
        "binSegment",
        "--outdir",
        str(outdir),
        "--sample",
        paths.sample,
        "--thread",
        str(values["thread"]),
        "--genomeDir",
        str(paths.genome_dir),
        "--pixel-size",
        str(values["pixel_size"]),
        "--input",
        str(input_dir),
        "--segment",
        "--model",
        str(paths.src_dir / "swin_tiny.pth"),
        "--count",
        "--count_detail",
        count_detail,
    ]
    method = get_method_module(paths.method)
    he_image = _planned_he_image(paths, input_dir) if method.requires_he_image else None
    method.extend_binsegment_command(
        command,
        sample=paths.sample,
        input_dir=input_dir,
        he_image=he_image,
        values=values,
    )
    if values["gene_mask_filter"] and paths.workflow != "SN":
        command.append("--gene-mask-filter")
    if values["fluorescence_background"]:
        command.append("--fluorescence-background")
    if values["cell_segmentation_preset"] == "dapi":
        command.append("--require-manual-he-mask")
    return StepPlan(
        "06.segment/01.binsegment",
        command,
        outputs=(outdir,),
    )


def _post_binsegment_steps(paths: RuntimePaths, values: dict[str, Any]) -> list[StepPlan]:
    bin_segment_dir = paths.sampledir / "06.segment/01.binsegment"
    steps: list[StepPlan] = []
    if values["enable_cavity_filter"]:
        cavity_outdir = bin_segment_dir / "cavity_filter"
        command = [
            "celatlas_spatial",
            "rna",
            "cavityFilter",
            "--sampledir",
            str(paths.sampledir),
            "--bin-segment-dir",
            str(bin_segment_dir),
            "--outdir",
            str(cavity_outdir),
            "--sample",
            paths.sample,
            "--bins",
            str(values["cavity_bins"]),
            "--mask-preset",
            str(values["cavity_mask_preset"]),
            "--min-component-ratio",
            str(values["cavity_min_component_ratio"]),
            "--min-hole-area",
            str(values["cavity_min_hole_area"]),
            "--close-radius",
            str(values["cavity_close_radius"]),
        ]
        if values["cavity_apply"]:
            command.append("--apply")
        if values["cavity_dry_run"]:
            command.append("--dry-run")
        if values["cavity_skip_qc_images"]:
            command.append("--skip-qc-images")
        if values["cavity_preserve_gem_support"]:
            command.append("--preserve-gem-support")
        if values["cavity_force"]:
            command.append("--force")
        steps.append(
            StepPlan(
                "06.segment/01.cavity_filter",
                command,
                outputs=(cavity_outdir,),
            )
        )

    if values["enable_stardist_cell_segment"]:
        cell_outdir = paths.sampledir / "06.segment/02.cellsegment"
        command = [
            "celatlas_spatial",
            "rna",
            "stardistCellSegment",
            "--sampledir",
            str(paths.sampledir),
            "--bin-segment-dir",
            str(bin_segment_dir),
            "--outdir",
            str(cell_outdir),
            "--sample",
            paths.sample,
            "--genomeDir",
            str(paths.genome_dir),
            "--runtime-input-dir",
            str(paths.runtime_mask_dir),
            "--model",
            str(values["stardist_model"]),
            "--prob-thresh",
            str(values["stardist_prob_thresh"]),
            "--max-dim",
            str(values["stardist_max_dim"]),
            "--scale",
            str(values["stardist_scale"]),
            "--n-tiles",
            str(values["stardist_n_tiles"]),
            "--expand-pixels",
            str(values["stardist_expand_pixels"]),
            "--min-umi",
            str(values["stardist_min_umi"]),
            "--min-genes",
            str(values["stardist_min_genes"]),
        ]
        optional_values = (
            ("--stardist-python", values["stardist_python"]),
            ("--labels", values["stardist_labels"]),
            ("--image", values["stardist_image"]),
            ("--tissue-bbox", values["stardist_tissue_bbox"]),
            ("--model-dir", values["stardist_model_dir"]),
            ("--nms-thresh", values["stardist_nms_thresh"]),
        )
        for option, value in optional_values:
            if value not in (None, ""):
                command.extend([option, str(value)])
        if values["stardist_labels"]:
            command.append("--skip-inference")
        if values["cell_segmentation_preset"] == "dapi":
            command.append("--require-registered-dapi")
            # Do not accidentally reuse a cavity mask from an older run.
            mask = bin_segment_dir / "images" / f"{paths.sample}_tissue_cut.tif"
            command.extend(["--barcode-mask", str(mask)])
        if values["stardist_skip_counts"]:
            command.append("--skip-counts")
        if values["stardist_no_label_output"]:
            command.append("--no-label-output")
        if values["stardist_tiled_inference"]:
            command.extend(
                [
                    "--tiled-inference",
                    "--tile-size",
                    str(values["stardist_tile_size"]),
                    "--tile-overlap",
                    str(values["stardist_tile_overlap"]),
                    "--tile-merge-overlap",
                    str(values["stardist_tile_merge_overlap"]),
                    "--fluorescence-channel",
                    str(values["stardist_fluorescence_channel"]),
                ]
            )
            if values["stardist_tile_cache_dir"]:
                command.extend(["--tile-cache-dir", str(values["stardist_tile_cache_dir"])])
            for rectangle in str(values["stardist_exclude_rectangle"] or "").split(";"):
                if rectangle.strip():
                    command.extend(["--exclude-rectangle", rectangle.strip()])
        steps.append(
            StepPlan(
                "06.segment/02.cellsegment",
                command,
                outputs=(cell_outdir,),
            )
        )
    return steps


def _analysis_steps(paths: RuntimePaths, values: dict[str, Any]) -> list[StepPlan]:
    outdir = paths.sampledir / "07.outs/binned_outputs"
    square_bin = paths.sampledir / "06.segment/01.binsegment/square_bin"
    command = [
        "celatlas_spatial",
        "rna",
        "analysis",
        "--outdir",
        str(outdir),
        "--sample",
        paths.sample,
        "--thread",
        str(values["thread"]),
        "--genomeDir",
        str(paths.genome_dir),
        "--square_bin_dir",
        str(square_bin),
        "--pixel-size",
        str(values["pixel_size"]),
        "--bin",
        str(values["bin"]),
        "--cluster-resolution",
        str(values["cluster_resolution"]),
        "--cell-min-genes",
        str(values["cell_min_genes"]),
        "--cell-min-counts",
        str(values["cell_min_counts"]),
        "--cell-max-genes",
        str(values["cell_max_genes"]),
        "--cell-max-counts",
        str(values["cell_max_counts"]),
        "--cell-max-mt",
        str(values["cell_max_mt"]),
    ]
    if str(values["bin"]) in {"10", "20"}:
        command.append("--skip-tsne")
    steps = [
        StepPlan(
            "07.outs/binned_outputs",
            command,
            outputs=(outdir,),
        )
    ]
    if values["enable_stardist_cell_segment"]:
        cell_outdir = paths.sampledir / "07.outs/cellsegmented_outputs"
        steps.append(
            StepPlan(
                "07.outs/cellsegmented_outputs",
                [
                    "celatlas_spatial",
                    "rna",
                    "analysis",
                    "--outdir",
                    str(paths.sampledir / "07.outs/cellsegmented_outputs"),
                    "--sample",
                    paths.sample,
                    "--thread",
                    str(values["thread"]),
                    "--genomeDir",
                    str(paths.genome_dir),
                    "--assay",
                    "cell",
                    "--cell-seg-dir",
                    str(paths.sampledir / "06.segment/02.cellsegment"),
                    "--hires-image",
                    str(paths.sampledir / "06.segment/01.binsegment/images/tissue_hires_image.png"),
                    "--fullres-image",
                    str(paths.sampledir / f"06.segment/01.binsegment/images/{paths.sample}_regist.tif"),
                    "--cell-cluster-resolution",
                    str(values["cell_cluster_resolution"]),
                    "--cell-n-neighbors",
                    str(values["cell_n_neighbors"]),
                    "--cell-n-pcs",
                    str(values["cell_n_pcs"]),
                    "--cell-min-genes",
                    str(values["cell_min_genes"]),
                    "--cell-min-counts",
                    str(values["cell_min_counts"]),
                    "--cell-max-genes",
                    str(values["cell_max_genes"]),
                    "--cell-max-counts",
                    str(values["cell_max_counts"]),
                    "--cell-max-mt",
                    str(values["cell_max_mt"]),
                    "--skip-tsne",
                ],
                outputs=(cell_outdir,),
            )
        )
    return steps


def _report_steps(paths: RuntimePaths, values: dict[str, Any]) -> list[StepPlan]:
    if paths.mode == "scrna":
        return [
            StepPlan(
                "08.report",
                [
                    "celatlas_scrna_report",
                    str(paths.sampledir),
                    paths.sample,
                    "--chemistry",
                    paths.chemistry,
                    "--species",
                    paths.species,
                    "--tissue",
                    str(values.get("tissue") or "N/A"),
                    "--output-filename",
                    f"{paths.sample}_scrna_analysis_report.html",
                    "--verbose",
                ],
                outputs=(paths.sampledir / f"{paths.sample}_scrna_analysis_report.html",),
            )
        ]

    command = [
        "celatlas_spatial_report",
        str(paths.sampledir),
        paths.sample,
        "--chemistry",
        paths.chemistry,
        "--species",
        paths.species,
        "--method",
        paths.method,
        "--tissue",
        str(values.get("tissue") or "N/A"),
        "--output-filename",
        f"{paths.sample}_spatial_analysis_report.html",
        "--verbose",
    ]
    if not values["enable_stardist_cell_segment"]:
        command.append("--exclude-cell-segmentation")
    return [StepPlan("08.report", command, outputs=(paths.sampledir / f"{paths.sample}_spatial_analysis_report.html",))]


def _values(row: dict[str, str], config: dict[str, Any], workflow: str, paths: RuntimePaths) -> dict[str, Any]:
    thread = _get(row, config, "thread", "default_thread", default=os.cpu_count() or 16)
    # Web workers set this explicitly in their transient systemd service.  Cap
    # the command-line thread arguments as well as BLAS/OpenMP environment
    # pools; otherwise a Research config with default_thread=32 can still
    # create a 32-thread featureCounts/binSegment process inside a worker that
    # was intended to be bounded to 12 native threads.
    web_thread_limit = os.environ.get("CELATLAS_WEB_NATIVE_THREADS", "").strip()
    if web_thread_limit.isdigit() and int(web_thread_limit) > 0:
        try:
            thread = min(int(thread), int(web_thread_limit))
        except (TypeError, ValueError):
            pass
    preset = _get(row, config, "cell_segmentation_preset", default="")
    if preset not in ("", "dapi"):
        raise PlanError(f"Unknown cell_segmentation_preset: {preset}")
    dapi = preset == "dapi"
    if dapi and (paths.method != "HE" or paths.mode != "strna"):
        raise PlanError("The dapi preset requires --image HE and --mode strna (manual ROI registration).")
    values = {
        "cell_segmentation_preset": preset,
        "tissue": _get(row, config, "tissue", default=""),
        "thread": thread,
        "star_thread": _star_thread(row, config, workflow, thread),
        "featurecounts_thread": _featurecounts_thread(row, config, workflow, thread),
        "bin": _get(row, config, "bin", "default_bin", default=50),
        "pixel_size": _get(row, config, "pixel_size", "default_pixel_size", default=0.5),
        "cluster_resolution": _get(row, config, "cluster_resolution", default=1.0),
        "insert_r2": _get(row, config, "insert_r2", "insertr2", default=150),
        "cell_num": _get(row, config, "cell_num", default=50000),
        "feature_type": _feature_type(row, config, workflow),
        "featurecounts_param": _featurecounts_param(row, config, workflow),
        "chemistry_pattern": _chemistry_pattern(paths.chemistry),
        "barcode_lownum": _barcode_lownum(row, config, workflow),
        "bbv4_strna_barcode_mismatch": _bbv4_mismatch(row, config, workflow),
        "max_parallel_files": _get(row, config, "max_parallel_files", default=3),
        "cutadapt_min_length": _cutadapt_value(row, config, workflow, "min_length"),
        "cutadapt_nextseq_trim": _cutadapt_value(row, config, workflow, "nextseq_trim"),
        "cutadapt_overlap": _cutadapt_value(row, config, workflow, "overlap"),
        "cutadapt_param": _cutadapt_param(row, config, workflow),
        "star_match_min": _star_value(row, config, workflow, paths.mode, paths.chemistry, "min"),
        "star_match_ratio": _star_value(row, config, workflow, paths.mode, paths.chemistry, "match_ratio"),
        "star_score_ratio": _star_value(row, config, workflow, paths.mode, paths.chemistry, "score_ratio"),
        "star_multimap": _star_value(row, config, workflow, paths.mode, paths.chemistry, "multimap"),
        "resolve_multigene_umi": _resolve_multigene_umi(row, config, workflow),
        "gene_mask_filter": _truthy(_get(row, config, "gene_mask_filter", default=False)),
        "fluorescence_background": dapi or _truthy(_get(row, config, "fluorescence_background", "CELATLAS_FLUORESCENCE_BACKGROUND", default=False)),
        "enable_cavity_filter": _truthy(_get(row, config, "enable_cavity_filter", default=False)),
        "cavity_apply": _truthy(_get(row, config, "cavity_apply", default=False)),
        "cavity_dry_run": _truthy(_get(row, config, "cavity_dry_run", default=False)),
        "cavity_skip_qc_images": _truthy(_get(row, config, "cavity_skip_qc_images", default=False)),
        "cavity_preserve_gem_support": _truthy(_get(row, config, "cavity_preserve_gem_support", default=False)),
        "cavity_force": _truthy(_get(row, config, "cavity_force", default=False)),
        "cavity_bins": _get(row, config, "cavity_bins", default="10,20,50,100,Raw"),
        "cavity_mask_preset": _get(row, config, "cavity_mask_preset", "mask_preset", default="default"),
        "cavity_min_component_ratio": _get(row, config, "cavity_min_component_ratio", default=0.01),
        "cavity_min_hole_area": _get(row, config, "cavity_min_hole_area", default=500),
        "cavity_close_radius": _get(row, config, "cavity_close_radius", default=20),
        "enable_stardist_cell_segment": dapi or _truthy(_get(row, config, "enable_stardist_cell_segment", "enable_stardist", default=False)),
        "stardist_python": _get(row, config, "stardist_python", "STARDIST_PYTHON", default=""),
        "stardist_labels": _get(row, config, "stardist_labels", "STARDIST_LABELS", default=""),
        "stardist_image": _get(row, config, "stardist_image", "STARDIST_IMAGE", default=""),
        "stardist_tissue_bbox": _get(row, config, "stardist_tissue_bbox", "STARDIST_TISSUE_BBOX", default=""),
        "stardist_model": _get(
            row,
            config,
            "stardist_model",
            "STARDIST_MODEL",
            default="2D_versatile_fluo" if dapi or paths.method == "ssDNA" else "2D_versatile_he",
        ),
        "stardist_model_dir": _get(row, config, "stardist_model_dir", "STARDIST_MODEL_DIR", default=""),
        "stardist_prob_thresh": _get(row, config, "stardist_prob_thresh", "STARDIST_PROB_THRESH", default=0.30),
        "stardist_nms_thresh": _get(row, config, "stardist_nms_thresh", "STARDIST_NMS_THRESH", default=0.3 if dapi else ""),
        "stardist_max_dim": _get(row, config, "stardist_max_dim", "STARDIST_MAX_DIM", default=0 if dapi else 6000),
        "stardist_scale": _get(row, config, "stardist_scale", "STARDIST_SCALE", default=1.0 if dapi else 2.0),
        "stardist_n_tiles": _get(row, config, "stardist_n_tiles", "STARDIST_N_TILES", default="2,2" if dapi else "4,4"),
        "stardist_expand_pixels": _get(row, config, "stardist_expand_pixels", "STARDIST_EXPAND_PIXELS", default=8),
        "stardist_min_umi": _get(row, config, "stardist_min_umi", "STARDIST_MIN_UMI", default=10),
        "stardist_min_genes": _get(row, config, "stardist_min_genes", "STARDIST_MIN_GENES", default=5),
        "stardist_skip_counts": _truthy(_get(row, config, "stardist_skip_counts", "STARDIST_SKIP_COUNTS", default=False)),
        "stardist_no_label_output": _truthy(_get(row, config, "stardist_no_label_output", "STARDIST_NO_LABEL_OUTPUT", default=dapi)),
        "stardist_tiled_inference": _truthy(_get(row, config, "stardist_tiled_inference", "STARDIST_TILED_INFERENCE", default=dapi)),
        "stardist_tile_size": _get(row, config, "stardist_tile_size", "STARDIST_TILE_SIZE", default=4096),
        "stardist_tile_overlap": _get(row, config, "stardist_tile_overlap", "STARDIST_TILE_OVERLAP", default=256),
        "stardist_tile_merge_overlap": _get(row, config, "stardist_tile_merge_overlap", "STARDIST_TILE_MERGE_OVERLAP", default=0.50),
        "stardist_fluorescence_channel": _get(row, config, "stardist_fluorescence_channel", "STARDIST_FLUORESCENCE_CHANNEL", default="blue" if dapi else "gray"),
        "stardist_tile_cache_dir": _get(row, config, "stardist_tile_cache_dir", "STARDIST_TILE_CACHE_DIR", default=""),
        "stardist_exclude_rectangle": _get(row, config, "stardist_exclude_rectangle", "STARDIST_EXCLUDE_RECTANGLE", default=""),
        "cell_cluster_resolution": _get(row, config, "cell_cluster_resolution", default=0.4),
        "cell_n_neighbors": _get(row, config, "cell_n_neighbors", default=10),
        "cell_n_pcs": _get(row, config, "cell_n_pcs", default=10),
        "cell_min_genes": _get(row, config, "cell_min_genes", default=0),
        "cell_min_counts": _get(row, config, "cell_min_counts", default=0),
        "cell_max_genes": _get(row, config, "cell_max_genes", default=0),
        "cell_max_counts": _get(row, config, "cell_max_counts", default=0),
        "cell_max_mt": _get(row, config, "cell_max_mt", default=100),
        "gem_bin_size": _get(row, config, "gem_bin_size", default=20),
        "ssdna_threshold_scale": _get(row, config, "ssdna_threshold_scale", default=1.0),
        "ssdna_mask_expand_pixels": _get(row, config, "ssdna_mask_expand_pixels", default=0),
        "ssdna_min_hole_area": _get(row, config, "ssdna_min_hole_area", default=5000),
        "umi_min_threshold": _get(row, config, "umi_min_threshold", default=30),
        "enhance_params": ENHANCE_PARAMS,
        "registration_type": _get(row, config, "registration_type", default="affine"),
        "skip_binsegment": _truthy(_get(row, config, "skip_binsegment", default=False)),
        "skip_analysis": _truthy(_get(row, config, "skip_analysis", default=False)),
        "skip_report": _truthy(_get(row, config, "skip_report", default=False)),
        # scRNA runs do not stage or consume spatial mask/image inputs.  Keep
        # this value unset so plan construction does not require a runtime
        # mask directory that is intentionally absent in scRNA mode.
        "spatial_input_dir": None if paths.mode == "scrna" else _spatial_input_dir(paths),
    }
    if dapi:
        if values["enable_cavity_filter"]:
            raise PlanError("DAPI uses the final ROI tissue mask; do not combine it with HE cavity filtering (--cavity-mode off).")
        registered = paths.sampledir / "06.segment/01.binsegment/images" / f"{paths.sample}_regist.tif"
        if values["stardist_image"] and Path(values["stardist_image"]).resolve() != registered.resolve():
            raise PlanError("The dapi preset segments the full-resolution registered TIFF only; remove stardist_image override.")
        values["stardist_image"] = str(registered)
        if (values["stardist_model"] != "2D_versatile_fluo" or not values["stardist_tiled_inference"]
                or float(values["stardist_scale"]) != 1 or int(values["stardist_max_dim"]) != 0):
            raise PlanError("The dapi preset requires fluo model, tiled inference, scale=1 and max_dim=0; remove conflicting StarDist settings.")
        if values["stardist_labels"] or values["stardist_tissue_bbox"] or values["stardist_skip_counts"]:
            raise PlanError("The one-pass dapi preset requires fresh registered-image inference and counts; remove labels/bbox/skip_counts overrides.")
    return values


def _spatial_input_dir(paths: RuntimePaths) -> Path:
    assert paths.runtime_mask_dir is not None
    return paths.runtime_mask_dir


def _planned_fastqs(paths: RuntimePaths) -> FastqInputs:
    if paths.fastq_dir is None or paths.fastq_name is None:
        raise FileNotFoundError("Cannot plan FASTQ paths without fastq_dir and fastq_name")
    return FastqInputs(
        paths.fastq_dir,
        paths.fastq_name,
        "planned_simple",
        (paths.fastq_dir / f"{paths.fastq_name}_1.fq.gz",),
        (paths.fastq_dir / f"{paths.fastq_name}_2.fq.gz",),
    )


def _planned_he_image(paths: RuntimePaths, input_dir: Path) -> Path:
    return find_he_image(input_dir, paths.sample) or find_he_image(paths.image_dir, paths.sample) or input_dir / f"{paths.sample}_he.tif"


def _get(row: dict[str, str], config: dict[str, Any], *keys: str, default: Any = None) -> Any:
    for key in keys:
        if row.get(key) not in (None, ""):
            return row[key]
    value = get_config_value(config, *keys)
    return default if value in (None, "") else value


def _feature_type(row: dict[str, str], config: dict[str, Any], workflow: str) -> str:
    if workflow == "SN":
        return str(_get(row, config, "sn_feature_type", "CELATLAS_SN_FEATURE_TYPE", default="gene"))
    return "gene"


def _featurecounts_param(row: dict[str, str], config: dict[str, Any], workflow: str) -> str:
    if workflow == "ST":
        return "-s 1"
    if workflow == "SX":
        return "-s 0 --fraction"
    if workflow == "SN":
        return str(_get(row, config, "sn_featurecounts_param", "CELATLAS_SN_FEATURECOUNTS_PARAM", default="-s 2"))
    return "-s 0 --fraction"


def _featurecounts_thread(row: dict[str, str], config: dict[str, Any], workflow: str, thread: Any) -> Any:
    configured = _get(row, config, "featurecounts_thread", "featurecounts_threads", default="")
    if configured not in (None, ""):
        return configured
    try:
        thread_int = int(thread)
    except (TypeError, ValueError):
        return thread
    if workflow == "SX":
        return min(thread_int, 8)
    return thread


def _star_thread(row: dict[str, str], config: dict[str, Any], workflow: str, thread: Any) -> Any:
    workflow_key = f"{workflow.lower()}_star_thread"
    configured = _get(row, config, workflow_key, "star_thread", "star_threads", "default_star_thread", default="")
    if configured not in (None, ""):
        return configured
    return thread


def _resolve_multigene_umi(row: dict[str, str], config: dict[str, Any], workflow: str) -> bool:
    if workflow == "SN":
        return _truthy(_get(row, config, "sn_resolve_multigene_umi", "CELATLAS_SN_RESOLVE_MULTIGENE_UMI", default=False))
    return _truthy(_get(row, config, "resolve_multigene_umi", default=workflow == "SX"))


def _barcode_lownum(row: dict[str, str], config: dict[str, Any], workflow: str) -> int:
    if workflow == "ST":
        return int(_get(row, config, "barcode_lownum", default=2))
    if workflow == "SN":
        return int(_get(row, config, "sn_barcode_lownum", "CELATLAS_SN_BARCODE_LOWNUM", default=1))
    return int(_get(row, config, "barcode_lownum", default=1))


def _bbv4_mismatch(row: dict[str, str], config: dict[str, Any], workflow: str) -> Any:
    if workflow in {"ST", "SX"}:
        return _get(row, config, "bbv4_strna_barcode_mismatch", "bbv4_strna_mismatch", default=2)
    return None


def _cutadapt_value(row: dict[str, str], config: dict[str, Any], workflow: str, name: str) -> Any:
    if workflow == "SN":
        keys = {
            "min_length": ("sn_cutadapt_min_length", "CELATLAS_SN_CUTADAPT_MIN_LENGTH"),
            "nextseq_trim": ("sn_cutadapt_nextseq_trim", "CELATLAS_SN_CUTADAPT_NEXTSEQ_TRIM"),
            "overlap": ("sn_cutadapt_overlap", "CELATLAS_SN_CUTADAPT_OVERLAP"),
        }[name]
        defaults = {"min_length": 15, "nextseq_trim": 20, "overlap": 10}
        return _get(row, config, *keys, default=defaults[name])
    return {"min_length": 20, "nextseq_trim": 20, "overlap": 10}[name]


def _cutadapt_param(row: dict[str, str], config: dict[str, Any], workflow: str) -> str:
    if workflow == "SX":
        return "--poly-a -a A{10}"
    if workflow == "SN":
        return str(_get(row, config, "sn_cutadapt_param", "CELATLAS_SN_CUTADAPT_PARAM", default="-a T{15} -g T{15}"))
    return str(_get(row, config, "cutadapt_param", default="") or "")


def _star_value(
    row: dict[str, str],
    config: dict[str, Any],
    workflow: str,
    mode: str,
    chemistry: str,
    name: str,
) -> Any:
    if workflow == "SN":
        prefix = "sn_scrna" if mode == "scrna" else "sn_strna"
        defaults = {
            "min": 15 if mode == "scrna" else 20,
            "match_ratio": 0.15 if mode == "scrna" else 0.2,
            "score_ratio": 0.15 if mode == "scrna" else 0.2,
            "multimap": 10,
        }
        if name == "multimap":
            return _get(row, config, "sn_star_multimap", "CELATLAS_SN_STAR_MULTIMAP", default=defaults[name])
        return _get(row, config, f"{prefix}_star_{name}", f"CELATLAS_{prefix.upper()}_STAR_{name.upper()}", default=defaults[name])
    if workflow == "SX":
        defaults = {
            "min": 30 if mode == "scrna" else 25,
            "match_ratio": 0.2,
            "score_ratio": 0.2,
            "multimap": 1 if mode == "scrna" else 10,
        }
        if name == "multimap":
            return _get(row, config, "star_multimap", default=defaults[name])
        return defaults[name]
    defaults = {
        "min": 30 if mode == "scrna" else (20 if chemistry in {"BBV4", "BBV4_L9"} else 15),
        "match_ratio": 0.2,
        "score_ratio": 0.2,
        "multimap": 1 if mode == "scrna" else (10 if chemistry in {"BBV4", "BBV4_L9"} else 1),
    }
    if name == "min":
        return _get(row, config, "star_match_min", default=defaults[name])
    if name == "match_ratio":
        return _get(row, config, "star_match_ratio", default=defaults[name])
    if name == "score_ratio":
        return _get(row, config, "star_score_ratio", default=defaults[name])
    return _get(row, config, "star_multimap", default=defaults[name])


def _chemistry_pattern(chemistry: str) -> str:
    if chemistry == "BBV4":
        return "C20L15U10T18"
    if chemistry == "BBV4_L9":
        return "C20L9U10T18"
    return "C4L15C4L15C4U10T18"


def _truthy(value: Any) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on", "enable", "enabled"}


def _normalize_step_selectors(value: str | list[str] | tuple[str, ...]) -> tuple[str, ...]:
    if isinstance(value, str):
        raw_items = value.split(",")
    else:
        raw_items = value
    return tuple(item.strip() for item in raw_items if item and item.strip())


def _selector_index(plans: list[StepPlan], selector: str | None, *, default: int) -> int:
    if not selector:
        return default
    for index, plan in enumerate(plans):
        if _step_matches(plan.name, selector.strip()):
            return index
    raise ValueError(f"Step selector not found: {selector}")


def _step_matches(step_name: str, selector: str) -> bool:
    if step_name == selector:
        return True
    if step_name.startswith(selector):
        return True
    prefix = step_name.split(".", 1)[0]
    return prefix == selector
